services:
    twig.declension:
        class: BubnovKelnik\TwigDeclensionBundle\Twig\Extension\TwigDeclensionExtension
        arguments: [@doctrine.orm.entity_manager, %locale%]
        tags:
            - { name: twig.extension }